api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

app_name = 'api'
urlpatterns = [
    # athlete
    path('athlete/', views.AthleteList.as_view()),
    path('athlete/<int:pk>/', views.AthleteDetail.as_view()),
    path('athlete/sort/<str:sortby>/', views.AthleteSorted.as_view()),

    # achievements
    path('achievement/', views.CollectionList.as_view()),
    path('achievement/<int:pk>', views.CollectionDetail.as_view()),

    # event
    path('event/', views.EventList.as_view()),
    path('event/<int:pk>', views.EventDetail.as_view()),

    # achievement mapping
    path('achievement-mapping/', views.AchievementMappingList.as_view()),
    path('achievement-mapping/<int:pk>',
         views.AchievementMappingDetail.as_view()),

    # achievement list
    path('achievement-list/', views.AchievementCollectionList.as_view()),
    path('achievement-list/<int:pk>',
         views.AchievementCollectionDetail.as_view()),

     # sport
    path('sport/', views.SportList.as_view()),
    path('sport/<int:pk>',
         views.SportDetail.as_view()),

     # athlete sports
    path('athlete-sports/', views.AthleteSportsList.as_view()),
    path('athlete-sports/<int:pk>',
         views.AthleteSportsDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

athletedb/urls.py
from django.urls import path

from . import views

app_name = 'athletedb'
urlpatterns = [
    # frontend
    path('', views.index, name='index'),
    path('atlet/<int:athlete_id>/', views.athlete_detail, name='athlete-detail'),
    path('prestasi/<int:achievement_id>/',
         views.achievement_detail, name='achievement-detail'),

]

proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('athletedb.urls')),
    path('api/', include('api.urls')),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT,})
]

athletedb/models.py
from django.db import models
from dateutil.relativedelta import relativedelta
from datetime import datetime
from model_utils import Choices

# Create your models here.


class Sport(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Cabang Olahraga'
        verbose_name_plural = 'Cabang Olahraga'
        db_table = 'athletedb_sport'

    @property
    def get_name_titled(self):
        return self.name.title()

    def save(self, *args, **kwargs):
        self.name = self.get_name_titled
        super(Sport, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=255)
    year = models.IntegerField(default=None, blank=True, null=True)
    # year = models.CharField(max_length=255)
    organizer = models.CharField(max_length=255)
    date = models.DateField(default=None, blank=True, null=True)
    # date = models.CharField(max_length=0)
    location = models.CharField(
        max_length=255, default=None, blank=True, null=True)

    class Meta:
        verbose_name = 'Olimpiade'
        verbose_name_plural = 'Olimpiade'
        db_table = 'athletedb_event'

    @property
    def get_name_titled(self):
        return self.name.title()

    @property
    def get_organizer_titled(self):
        return self.organizer.title()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.get_name_titled
        self.organizer = self.get_organizer_titled
        super(Event, self).save(*args, **kwargs)


class AchievementList(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'Perolehan Medali'
        verbose_name_plural = 'Perolehan Medali'
        db_table = 'athletedb_achievementlist'

    @property
    def get_name_titled(self):
        return self.name.title()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.get_name_titled
        super(AchievementList, self).save(*args, **kwargs)


class Athlete(models.Model):
    name = models.CharField(max_length=200, verbose_name='nama')
    nik = models.CharField(
        max_length=255, default=None, blank=True, null=True, unique=True)
    photo = models.ImageField(upload_to='images/pasfoto/',
                              default='images/pasfoto/default_photo.jpg',
                              blank=True, null=True,
                              verbose_name='Pasfoto')
    ktp = models.ImageField(upload_to='images/ktp/',
                            default=None, blank=True, null=True, verbose_name='Foto Ktp')
    kk = models.ImageField(upload_to='images/kartu-keluarga/',
                           default=None, blank=True, null=True,
                           verbose_name='Foto Kartu Keluarga')
    email = models.EmailField(default=None, blank=True, null=True)
    birth_date = models.DateField(
        default=None, blank=True, null=True, verbose_name='tanggal lahir')
    birth_place = models.CharField(
        max_length=255, default=None, blank=True, null=True,
        verbose_name='tempat lahir')
    age = models.IntegerField(default=None, blank=True,
                              null=True, verbose_name='umur')
    BLOOD_TYPES = Choices('A', 'B', 'AB', 'O')
    blood_type = models.CharField(
        choices=BLOOD_TYPES, default=BLOOD_TYPES.A,
        max_length=2, blank=True, null=True, verbose_name='golongan darah')
    phone_number = models.CharField(
        max_length=50, default=None, blank=True, null=True, verbose_name='nomor telepon')
    address = models.CharField(
        max_length=255, default=None, blank=True, null=True, verbose_name='alamat')
    school = models.CharField(
        max_length=255, default=None, blank=True, null=True, verbose_name='sekolah')

    SEXES = Choices('Laki - laki', 'Perempuan')
    sex = models.CharField(
        choices=SEXES, max_length=20,
        blank=True, null=True, verbose_name='Jenis Kelamin'
    )
    sports = models.ManyToManyField(Sport, verbose_name='Cabang Olahraga')

    class Meta:
        ordering = ['-id']
        verbose_name = 'Atlet'
        verbose_name_plural = 'Atlet'
        db_table = 'athletedb_athlete'

    def __str__(self):
        return self.name

    @property
    def get_age(self):
        return relativedelta(datetime.today(), self.birth_date).years

    @property
    def get_name_titled(self):
        return self.name.title()

    def save(self, *args, **kwargs):
        self.age = self.get_age
        self.name = self.get_name_titled
        super(Athlete, self).save(*args, **kwargs)


class Achievement(models.Model):
    # description = models.CharField(
    #     max_length=255, verbose_name='Deskripsi',
    #     default=None, blank=True, null=True)
    description = models.TextField(
        verbose_name='Deskripsi',
        default=None, blank=True, null=True
    )

    RESULTS = Choices('Juara 1', 'Juara 2', 'Juara 3', 'Peserta')
    result = models.CharField(
        choices=RESULTS, max_length=10, verbose_name='Hasil',
        default=None, blank=True, null=True)

    LEVELS = Choices('Tingkat Kota (Porkot)', 'Tingkat Daerah (Porda)',
                     'Tingkat Provinsi (Porprov)', 'Tingkat Nasional (PON)',
                     'Tingkat Dunia (Kejurda)')
    level = models.CharField(
        choices=LEVELS, max_length=255, verbose_name='Tingkat kejuaraan',
        default=None, blank=True, null=True)
    certificate_file = models.ImageField(
        upload_to='images/sertifikat/', blank=True,
        null=True, verbose_name='File sertifikat')
    athlete = models.ForeignKey(
        Athlete, on_delete=models.CASCADE,
        related_name='achievements',
        default=None, blank=True, null=True
    )

    class Meta:
        verbose_name = 'Prestasi'
        verbose_name_plural = 'Prestasi'
        db_table = 'athletedb_achievement'

    def __str__(self):
        return "{result}, {level}".format(result=self.result, level=self.level)


class AchievementMapping(models.Model):
    athlete = models.ForeignKey(
        Athlete, related_name='athletes_achievementmapping', on_delete=models.CASCADE)
    event = models.ForeignKey(
        Event, related_name='events_achievementmapping', on_delete=models.CASCADE)
    achievement = models.ForeignKey(
        AchievementList, related_name='achievementlist_achievementmapping',
        on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Medali Prestasi'
        verbose_name_plural = 'Medali Prestasi'
        db_table = 'athletedb_achievementmapping'

    def __str__(self):
        return self.athlete.name


class AthleteSports(models.Model):
    athlete = models.ForeignKey(
        Athlete, related_name='athletes_athletesports', on_delete=models.CASCADE)
    sport = models.ForeignKey(
        Sport, related_name='sports_athletesports', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Olahraga atlit'
        verbose_name_plural = 'Olahraga atlit'
        db_table = 'athletedb_athletesports'

    def __str__(self):
        return self.sport.name

athletedb/views.py
from django.shortcuts import (
    render, get_object_or_404)
from django.http import HttpResponse, Http404
from django.template import loader
from .models import Athlete, Achievement
from django.http import JsonResponse
from django.core.paginator import (
    Paginator, EmptyPage, PageNotAnInteger)

# pylint: disable=no-member


def index(request):
    athlete_list = Athlete.objects.all()

    athlete_name = request.GET.get('athlete')
    if athlete_name:
        athlete_list = athlete_list.filter(
            name__icontains=athlete_name)

    sport_name = request.GET.get('sports')
    if sport_name:
        athlete_list = athlete_list.filter(
            sports__name__icontains=sport_name
        )

    page = request.GET.get('page', 1)

    paginator = Paginator(athlete_list, 20)

    try:
        athletes = paginator.page(page)
    except PageNotAnInteger:
        athletes = paginator.page(1)
    except EmptyPage:
        athletes = paginator.page(paginator.num_pages)

    context = {
        'athlete_list': athletes,
    }
    return render(request, 'athletedb/index.html', context)


def athlete_detail(request, athlete_id):
    athlete_detail = get_object_or_404(Athlete, pk=athlete_id)
    return render(
        request,
        'athletedb/athlete_detail.html',
        {'athlete_detail': athlete_detail}
    )


def achievement_detail(request, achievement_id):
    achievement_detail = get_object_or_404(Achievement, pk=achievement_id)
    return render(
        request,
        'athletedb/achievement_detail.html',
        {'achievement_detail': achievement_detail}
    )

athletedb/templates/athletedb/achievement_detail.html
{% extends "athletedb/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'athletedb/css/achievement_detail.css' %}">
{% endblock %}
{% block content %}
<h2>{{ achievement_detail.title }}</h2>

<p>{{ achievement_detail.description }}</p>

<table class="table">
    <thead></thead>
    <tbody>
        <tr>
            <td class="font-weight-bold">Nama</td>
            <td>{{ achievement_detail.title }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold">Pelaksana</td>
            <td>{{ achievement_detail.organizer }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold">Lokasi</td>
            <td>{{ achievement_detail.location }}</td>
        </tr>
        <tr>
            <td class="font-weight-bold">Tanggal</td>
            <td>{{ achievement_detail.date }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

athletedb/templates/athletedb/athlete_detail.html
{% extends "athletedb/base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'athletedb/css/athlete_detail.css' %}">
{% endblock %}
{% block content %}

<div class="athlete-bio shadow-sm p-4 mb-4 bg-white">

    <div class="row align-items-center profile-header">
        {% if athlete_detail.photo %}
        <div class="col- athlete-photo">
            <img src="{{ athlete_detail.photo.url }}" class="rounded-circle" alt="Pasfoto" width="150" height="150">
        </div>
        {% endif %}
        <div class="col-sm athlete_name">
            <h2 class="athlete_name_title"></h2>
        </div>
    </div>

    <dl class="row athlete-bio-detail">
        <dt class="col-sm-3">Nama</dt>
        <dd class="col-sm-9" id="athlete-name"></dd>

        <dt class="col-sm-3">NIK</dt>
        <dd class="col-sm-9" id="athlete-nik"></dd>

        <dt class="col-sm-3">Tanggal Lahir</dt>
        <dd class="col-sm-9" id="athlete-birthdate"></dd>

        <dt class="col-sm-3">Tempat Lahir</dt>
        <dd class="col-sm-9" id="athlete-birthplace"></dd>

        <dt class="col-sm-3">Jenis Kelamin</dt>
        <dd class="col-sm-9" id="athlete-sex"></dd>

        <dt class="col-sm-3">Golongan Darah</dt>
        <dd class="col-sm-9" id="athlete-bloodtype"></dd>

        <dt class="col-sm-3">Nomor Telepon</dt>
        <dd class="col-sm-9" id="athlete-phone"></dd>

        <dt class="col-sm-3">Alamat</dt>
        <dd class="col-sm-9" id="athlete-address"></dd>

        <dt class="col-sm-3">Email</dt>
        <dd class="col-sm-9" id="athlete-email"></dd>

        <dt class="col-sm-3">Asal Sekolah</dt>
        <dd class="col-sm-9" id="athlete-school"></dd>

        <dt class="col-sm-3">Cabang Olahraga</dt>
    </dl>
</div>



<div class="achievement-athlete-master shadow-sm p-4 mb-4 bg-white">
    <h3>Prestasi</h3>
    <div class="achievement-list"></div>
    <div class="accordion" id="accordionAchievement">
    </div>

</div>
{% endblock %}

{% block js %}
<script src="{% static 'athletedb/js/athlete-detail.js' %}">
</script>
{% endblock %}

athletedb/templates/athletedb/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/ico" href="{% static 'athletedb/image/database-1-24.png' %}" />
    <link rel="stylesheet" href="{% static 'athletedb/css/bootstrap.css' %}">
    {% block css %}
    {% endblock %}
    <link href="https://fonts.googleapis.com/css?family=Cabin&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <title>Database Atlet Depok</title>
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'athletedb:index' %}">
                <img class="align-middle" src="{% static 'athletedb/image/logo.svg' %}" width="70" height="70"
                    class="d-inline-block align-top" alt="">
                <span class="navbar-title align-middle font-weight-bold">Database Atlet Kota Depok</span>
            </a>
            {% block search %}
            {% endblock %}
        </nav>

        {% block content %}
        {% endblock %}
    </div>

    {% block js %}
    {% endblock %}
</body>

</html>

athletedb/templates/athletedb/index.html
{% extends "athletedb/base.html" %}
{% load static %}

{% load templatehelpers %}

{% block css %}
<link rel="stylesheet" href="{% static 'athletedb/css/index.css' %}">
{% endblock %}

{% block search %}
<form class="form-inline">
  <div class="input-group">
    <input type="text" class="form-control" name="athlete" aria-label="Text input with dropdown button"
      placeholder="Cari atlet dan lainnya ...">
    <div class="input-group-append">
      <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false">Atlet</button>
      <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item" data-category="athlete">Atlet</a>
        <a class="dropdown-item" data-category="sports">Cabang Olahraga</a>
      </div>
    </div>
  </div>
</form>
{% endblock %}

{% block content %}
{% if athlete_list %}
<div class="content-table">
  <table id="athlete-table" class="table">
    <thead class="thead-dark">
      <tr>
        <!-- <th scope="col">Nama <img class="sort-name" src="{% static 'athletedb/image/iconmonstr-sort-7-12.png' %}"
                      alt=""></th> -->
        <th scope="col">Nama</th>
        <!-- <th scope="col">Umur <img class="sort-age" src="{% static 'athletedb/image/iconmonstr-sort-7-12.png' %}"
                      alt=""></th> -->
        <th scope="col">Umur</th>
        <th scope="col">Tanggal Lahir</th>
        <th scope="col">Alamat</th>
        <th scope="col">Cabor</th>
      </tr>
    </thead>
    <tbody class="athlete-data">
    </tbody>
  </table>
</div>
{% if athlete_list.has_other_pages %}
<ul class="pagination justify-content-end">
  <!-- <h2>{% relative_url 'name' 'order' request.GET.urlencode %}</h2> -->

  {% if athlete_list.has_previous %}
  <!-- <li class="page-item"><a class="page-link" href="?page={{ athlete_list.previous_page_number }}">&laquo;</a></li> -->
  <li class="page-item"><a class="page-link"
      href="{% relative_url athlete_list.previous_page_number 'page' request.GET.urlencode %}">&laquo;</a></li>
  {% else %}
  <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
  {% endif %}
  {% for i in athlete_list.paginator.page_range %}
  {% if athlete_list.number == i %}
  <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
  {% else %}
  <!-- <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li> -->
  <li class="page-item"><a class="page-link" href="{% relative_url i 'page' request.GET.urlencode %}">{{ i }}</a></li>
  {% endif %}
  {% endfor %}
  {% if athlete_list.has_next %}
  <!-- <li class="page-item"><a class="page-link" href="?page={{ athlete_list.next_page_number }}">&raquo;</a></li> -->
  <li class="page-item"><a class="page-link"
      href="{% relative_url athlete_list.next_page_number 'page' request.GET.urlencode %}">&raquo;</a></li>
  {% else %}
  <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
  {% endif %}
</ul>
{% endif %}

{% else %}
<p>Tidak ada data.</p>
{% endif %}
{% endblock %}

{% block js %}
<script src="{% static 'athletedb/js/index.js' %}">
</script>
{% endblock %}